### ISSUE TITLE
Code doesn't work on Mac. 

### ISSUE THREAD

**Issue by joemac638** [devo-id/ATM-system-GUI#2]
Adding screen shots without changing code. Am I missing something?

**Comment by devo-id** [comment]
I have updated the code for the issue, and tested it for both Mac and windows. 
Elaborate the issue that you are facing.

**Comment by joemac638** [comment]
Sorry, but cannot locate updated code.

**Comment by devo-id** [comment]
Refer to this commit: [Fix](https://github.com/devo-id/ATM-system-GUI/commit/7cb8bfb5f98409519e395c621621d4e1c37bc811)
